
CREATE DATABASE inventario;
USE inventario;

CREATE TABLE producto(id INT AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(50),descripcion VARCHAR(100),cantidad INT,precio DOUBLE);
CREATE TABLE inventario(id INT AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(50));
CREATE TABLE proveedor(id INT AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(50));
CREATE TABLE cliente(id INT AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(50));
CREATE TABLE venta(id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE factura(id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE detallefactura(id INT AUTO_INCREMENT PRIMARY KEY);
